version: '3.7'
services:

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - '8080:8080'
    volumes:
      - ./volumes/nifi/jdbc:/opt/jdbc
      - ./volumes/nifi/data:/opt/nifi/data
      - ./volumes/nifi/properties:/opt/nifi/nifi-current/properties  #credentials.properties
      - ./volumes/nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./volumes/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./volumes/nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./volumes/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
    environment:
      NIFI_WEB_HTTP_PORT: 8080
      #SINGLE_USER_CREDENTIALS_USERNAME: admin
      #SINGLE_USER_CREDENTIALS_PASSWORD: 000000000000  #minimo de 12 caracteres


  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifi-registry
    ports:
      - '18080:18080'
    volumes:
      - ./volumes/nifi-registry/nifi.properties:/nifi.properties
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./volumes/minio/nifi.properties:/nifi.properties
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_STORAGE_USE_HTTPS: False
    command: server /nifi.properties --console-address ":9001"


  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres/nifi.properties:/nifi.properties
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123

