apiVersion: v1
kind: Service
metadata:
  name: nifi-svc
  namespace: nifi
spec:
  selector:
    app: nifi
  type: LoadBalancer
  ports:
    - name: "9011"
      port: 9011
      targetPort: 9011

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  namespace: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      securityContext:
        runAsUser: 0  # Definindo o usuário root
      containers:
      - name: nifi
        image: apache/nifi:latest
        ports:
        - containerPort: 9011
        env:
          - name: NIFI_WEB_HTTP_PORT
            value: "9011"
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: nifi-registry-svc
  namespace: nifi
spec:
  selector:
    app: nifi-registry
  type: LoadBalancer
  ports:
    - name: "18080"
      port: 18080
      targetPort: 18080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi-registry
  namespace: nifi
  labels:
    app: nifi-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi-registry
  template:
    metadata:
      labels:
        app: nifi-registry
    spec:
      containers:
        - name: nifi-registry
          image: apache/nifi-registry:latest
          ports:
            - containerPort: 18080
          env:
            - name: NIFI_REGISTRY_WEB_HTTP_PORT
              value: "18080"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: nifi
spec:
  selector:
    app: postgres
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: "5432"
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres123
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /nifi.properties/postgres
      volumes:
        - name: pgdata
          emptyDir: {}
---



